# Generated by Django 2.2 on 2019-04-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='userspace.Post'),
        ),
    ]
